### ISSUE TITLE
Crash on JDK 9

### ISSUE THREAD

**Issue by wispborne** [davidwhitman/stories#14]
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "clazz" is null
2	java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "clazz" is null
3	at org.apache.log4j.Logger.getLogger(Logger.java:107)
4	at wisp.questgiver.wispLib.DebugLogger.i(Logger.kt:121)
5	at wisp.questgiver.wispLib.DebugLogger.i$default(Logger.kt:33)
6	at org.wisp.stories.LifecyclePlugin.readConfiguration(LifecyclePlugin.kt:206)
7	at org.wisp.stories.LifecyclePlugin.onGameLoad(LifecyclePlugin.kt:62)
8	at com.fs.starfarer.campaign.save.CampaignGameManager.o00000(Unknown Source)
9	at com.fs.starfarer.title.TitleScreenState.dialogDismissed(Unknown Source)
10	at com.fs.starfarer.ui.Oo0O.dismiss(Unknown Source)
11	at com.fs.starfarer.ui.impl.o0oO.dismiss(Unknown Source)
12	at com.fs.starfarer.campaign.save.J.actionPerformed(Unknown Source)
13	at com.fs.starfarer.ui.newnew.buttonPressed(Unknown Source)
14	at com.fs.starfarer.ui.I.ﾃ・0000(Unknown Source)
15	at com.fs.starfarer.ui.I.processInput(Unknown Source)
16	at com.fs.starfarer.ui.Stringsuper.super(Unknown Source)
17	at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
18	at com.fs.state.AppDriver.begin(Unknown Source)
19	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
20	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
21	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
22	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by EngineOfDarkness** [comment]
Is this complicated to fix?

This prevents loading existing saves or starting new ones (both crash while loading) on JDK 17 using https://github.com/necauqua/starsector-fixes/

See https://github.com/necauqua/starsector-fixes/issues/3

Edit: 

Ah I assume this has been fixed already (going by the below commit) but isn't released in the current version `2.0.3-rc2` of Persean Chronicles ?

https://github.com/wispborne/questgiver/commit/d28185150309682abd45d7e6c3a17607dbda4659

**Comment by wispborne** [comment]
@EngineOfDarkness correct, it's fixed but unreleased due to so few people using anything above JRE 8.

Here's a hotfix; I think all you should need is `libs/Questgiver-3.1.0.jar` but this is the full tag, minus a few unused files to shrink it below the 25 MB upload limit.

[persean-chronicles-2.1.0-jre9plus-hotfix.zip](https://github.com/wispborne/stories/files/10254564/persean-chronicles-2.1.0-jre9plus-hotfix.zip)

**Comment by EngineOfDarkness** [comment]
@wispborne  I can confirm that the my existing savegame now loads - thank you very much.
